In [2]:
%matplotlib inline
import pandas as pd

In [3]:
cast = pd.read_csv('F://AIX Docs//Data science//Python//datasets//cast.csv')
cast.head()

                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4   NaN
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

### How many movies are listed in the titles dataframe?

In [4]:
cast.title.value_counts().sum()

3611212

### What are the earliest two films listed in the titles dataframe?

In [75]:
cast.sort_values('year').head(2)['title']

2514470    Miss Jerry
555929     Miss Jerry
Name: title, dtype: object

In [76]:
cast.sort_values('year').head(2)

,title,year,name,type,character,n
2514470,Miss Jerry,1894,Blanche Bayliss,actress,Miss Geraldine Holbrook (Miss Jerry),NaN
555929,Miss Jerry,1894,Chauncey Depew,actor,Himself - the Director of the New York Central...,NaN

### How many movies have the title "Hamlet"?

In [77]:
len(cast[cast.title=='Hamlet'])

313

In [78]:
cast[cast.title=='Hamlet']

,title,year,name,type,character,n
1615,Hamlet,1996,Riz Abbasi,actor,Attendant to Claudius,1.0
7438,Hamlet,1921,Fritz Achterberg,actor,"Fortinbras,",9.0
11242,Hamlet,2009,Hayden Adams,actor,Laertes,7.0
11243,Hamlet,2009,Hayden Adams,actor,Player,7.0
13907,Hamlet,1913,Eric Adeney,actor,Reynaldo,14.0
16079,Hamlet,2000,Casey Affleck,actor,Fortinbras,15.0
32916,Hamlet,1964,Hugh Alexander,actor,Cornelius,NaN
32917,Hamlet,1964,Hugh Alexander,actor,Second Gravedigger,NaN
32918,Hamlet,1964,Hugh Alexander,actor,English Ambassador,NaN
52487,Hamlet,1913,Richard Andean,actor,Second Player,16.0
62270,Hamlet,1990,Christien Anholt,actor,Marcellus,14.0
74921,Hamlet,1969,Ben Aris,actor,Rosencrantz,8.0
80019,Hamlet,2015,Thomas (II) Arnold,actor,Horatio,5.0
92106,Hamlet,1996,Richard Attenborough,actor,English Ambassador,2.0
100256,Hamlet,1948,Felix Aylmer,actor,Polonius - Lord Chamberlain,15.0
132982,Hamlet,1913,J.H. Barnes,actor,Polonius,4.0
140011,Hamlet,2000,Paul Bartel,actor,Osric,14.0
145844,Hamlet,1990,Alan Bates,actor,Claudius,3.0
152349,Hamlet,1996,Simon Russell Beale,actor,Second Gravedigger,37.0
153202,Hamlet,1973,James Bearden,actor,Fortinbras,NaN
174961,Hamlet,1913,Grendon Bentley,actor,Fortinbras,7.0
206181,Hamlet,1996,David (V) Blair,actor,Attendant to Claudius,3.0
211111,Hamlet,1996,Brian Blessed,actor,Ghost of Hamlet's Father,4.0
241315,Hamlet,1996,Christopher Bowles,actor,Cadet in Play,NaN
250281,Hamlet,1996,Kenneth Branagh,actor,Hamlet,5.0
262368,Hamlet,1996,Richard Briers,actor,Polonius,6.0
283598,Hamlet,1996,Michael Bryant,actor,Priest,7.0
301167,Hamlet,1964,Richard Burton,actor,Hamlet,1.0
302715,Hamlet,1973,Stephen Bush,actor,Polonius,NaN
302796,Hamlet,1948,Anthony Bushell,actor,Bit Part,NaN
...,...,...,...,...,...,...
3137189,Hamlet,2015,Jodie McNee,actress,Rosencrantz,10.0
3137190,Hamlet,2015,Jodie McNee,actress,2nd Gravedigger,10.0
3140147,Hamlet,2009,Jennifer Mefford,actress,Player Queen,9.0
3140148,Hamlet,2009,Jennifer Mefford,actress,Messenger,9.0
3159950,Hamlet,1976,Helen Mirren,actress,Ophelia,2.0
3159951,Hamlet,1976,Helen Mirren,actress,Gertrude,2.0
3209199,Hamlet,1921,Asta Nielsen,actress,Hamlet,1.0
3211993,Hamlet,2000,Anne (II) Nixon,actress,Special Guest Appearance,34.0
3246370,Hamlet,1969,Judy Parfitt,actress,Gertrude,2.0
3256505,Hamlet,2015,Maxine Peake,actress,Hamlet,1.0
3269745,Hamlet,1990,Sarah Phillips,actress,The Players,19.0
3298558,Hamlet,1996,Sian Radinger,actress,Prologue,35.0
3303304,Hamlet,1996,Melanie Ramsay,actress,Prostitute,NaN
3310928,Hamlet,2000,India Reed Kotis,actress,Special Guest Appearance,29.0
3317452,Hamlet,1987,Melanie Revell,actress,Gertrude,NaN
3322807,Hamlet,1913,Olive Richardson,actress,Player Queen,NaN
3369033,Hamlet,1911,Emilie Sannom,actress,Ophelia,4.0
3387891,Hamlet,2000,Kelly Sebastian,actress,Secretary,39.0
3413503,Hamlet,1948,Jean Simmons,actress,Ophelia - and Daughter,17.0
3415452,Hamlet,1990,Baby Simon Sinclair,actress,The Players,26.0
3415596,Hamlet,1990,Pamela Sinclair,actress,The Players,25.0
3416831,Hamlet,1954,Mala Sinha,actress,Ophelia,1.0
3450159,Hamlet,2000,Julia Stiles,actress,Ophelia,7.0
3459439,Hamlet,2009,Bernadette Sullivan,actress,Gertrude,2.0
3479394,Hamlet,1964,Carol Teitel,actress,Lady,NaN
3505738,Hamlet,1969,Jennifer Tudor,actress,Court lady,23.0
3528322,Hamlet,2000,Diane Venora,actress,Gertrude,3.0
3557773,Hamlet,1996,Perdita Weeks,actress,Second Player,44.0
3562331,Hamlet,2015,Katie (II) West,actress,Ophelia,7.0
3578802,Hamlet,1996,Kate Winslet,actress,Ophelia,46.0

### How many movies are titled "North by Northwest"?

In [79]:
len(cast[cast.title=="North by Northwest"])

112

In [80]:
cast[cast.title=="North by Northwest"]

,title,year,name,type,character,n
12151,North by Northwest,1959,Stanley Adams,actor,Lieutenant Harding,NaN
27852,North by Northwest,1959,Andy Albin,actor,Farmer,NaN
54093,North by Northwest,1959,Don Anderson,actor,Worker,NaN
54307,North by Northwest,1959,Ernest Anderson,actor,Porter on Twentieth Century Ltd.,NaN
92195,North by Northwest,1959,Malcolm Atterbury,actor,Man at Prairie Crossing,NaN
97833,North by Northwest,1959,Tol Avery,actor,State Police Detective,NaN
109025,North by Northwest,1959,Sam Bagley,actor,Courtroom Spectator,NaN
114334,North by Northwest,1959,Frank Baker,actor,Man at Auction,NaN
137656,North by Northwest,1959,Baynes Barron,actor,Taxi Driver #2,NaN
151717,North by Northwest,1959,Brandon Beach,actor,Man at Auction,NaN
176030,North by Northwest,1959,John Beradino,actor,Sergeant Emile Klinger,NaN
198496,North by Northwest,1959,Edward Binns,actor,Captain Junket,15.0
222299,North by Northwest,1959,Stephen Bolster,actor,Man with Camera,NaN
343701,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5.0
344204,North by Northwest,1959,Steve Carruthers,actor,Man at Auction,NaN
350192,North by Northwest,1959,Taggart Casey,actor,Shaving Man,NaN
356803,North by Northwest,1959,Bill Catching,actor,Auction Attendant,NaN
424676,North by Northwest,1959,Bob (II) Coe,actor,Cropduster Pilot,NaN
447893,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13.0
467714,North by Northwest,1959,David A. Cox,actor,Police Officer on Horse,NaN
468709,North by Northwest,1959,Walter Coy,actor,U.S. Intelligence Agency Official,NaN
479498,North by Northwest,1959,Jimmy Cross,actor,Taxi Driver #1,NaN
502759,North by Northwest,1959,Jack Daly,actor,Train Steward,NaN
503758,North by Northwest,1959,John Damler,actor,Police Lieutenant,NaN
581619,North by Northwest,1959,Lawrence Dobkin,actor,U.S. Intelligence Agency Official,NaN
605839,North by Northwest,1959,Alphonso DuBois,actor,Man at United Nations Building,NaN
642085,North by Northwest,1959,Robert Ellenstein,actor,Licht,11.0
679471,North by Northwest,1959,Tommy Farrell,actor,Eddie - Elevator Starter,NaN
682655,North by Northwest,1959,Adolph Faylauer,actor,Bald Bidder,NaN
786648,North by Northwest,1959,Paul Genge,actor,Lieutenant Hagerman,NaN
...,...,...,...,...,...,...
2207044,North by Northwest,1959,Arthur Tovey,actor,Man at Auction,NaN
2212083,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12.0
2251621,North by Northwest,1959,Dale Van Sickel,actor,Ranger,NaN
2325131,North by Northwest,1959,Ray Weaver,actor,Policeman at Grand Central Station,NaN
2353592,North by Northwest,1959,Frank Wilcox,actor,Herman Weitner,NaN
2357939,North by Northwest,1959,Adam Williams,actor,Valerian,9.0
2362461,North by Northwest,1959,Lloyd (VI) Williams,actor,Minor Role,NaN
2363681,North by Northwest,1959,Robert Williams,actor,Patrolman Waggoner,NaN
2387386,North by Northwest,1959,Wilson Wood,actor,Photographer at United Nations,NaN
2412181,North by Northwest,1959,Carleton Young,actor,Fanning Nelson,NaN
2421836,North by Northwest,1959,Ernesto Zambrano,actor,Man at Auction,NaN
2465523,North by Northwest,1959,Anne (II) Anderson,actress,Woman,NaN
2670589,North by Northwest,1959,Lucille Curtis,actress,Woman,NaN
2671331,North by Northwest,1959,Patricia Cutts,actress,Hospital Patient,NaN
2766221,North by Northwest,1959,Jesslyn Fax,actress,Minor Role,NaN
2782130,North by Northwest,1959,Bess Flowers,actress,Hotel Lounge Patron,NaN
2786977,North by Northwest,1959,Josephine Forsberg,actress,Friendly Passenger,NaN
2793447,North by Northwest,1959,Sally Fraser,actress,Second United Nations Receptionist,NaN
2923056,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6.0
2979448,North by Northwest,1959,Madge Kennedy,actress,Mrs. Finlay,NaN
3024085,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4.0
3025468,North by Northwest,1959,Doreen Lang,actress,Maggie - Roger's Secretary,NaN
3107714,North by Northwest,1959,Nora Marlowe,actress,Anna - Housekeeper,NaN
3132085,North by Northwest,1959,Maura McGiveney,actress,Attendant,NaN
3289400,North by Northwest,1959,Maudie Prickett,actress,Elsie - Maid,NaN
3361396,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2.0
3416124,North by Northwest,1959,Doris Singh,actress,First United Nations Receptionist,NaN
3437248,North by Northwest,1959,Helen Spring,actress,Bidder,NaN
3567500,North by Northwest,1959,Susan Whitney,actress,Attendant,NaN
3578877,North by Northwest,1959,Paula Winslowe,actress,Woman at Auction,NaN

### When was the first movie titled "Hamlet" made?

In [81]:
cast[cast.title=="Hamlet"].sort_values('year').head(1)['year']

1545289    1910
Name: year, dtype: int64

In [82]:
cast[cast.title=="Hamlet"].sort_values('year')

,title,year,name,type,character,n
1545289,Hamlet,1910,Jean Mounet-Sully,actor,Hamlet,NaN
1233662,Hamlet,1911,Oscar Langkilde,actor,Horatio,6.0
2422953,Hamlet,1911,Einar Zangenberg,actor,Laertes,5.0
3015440,Hamlet,1911,Ella La Cour,actress,Gertrude,3.0
1592118,Hamlet,1911,Alwin Neu?,actor,Hamlet,1.0
954648,Hamlet,1911,Aage Hertel,actor,Claudius,2.0
3369033,Hamlet,1911,Emilie Sannom,actress,Ophelia,4.0
720239,Hamlet,1913,Johnston Forbes-Robertson,actor,Hamlet,2.0
1839655,Hamlet,1913,Percy Rhodes,actor,The Ghost,6.0
1843850,Hamlet,1913,G. (II) Richards,actor,Bernardo,12.0
1853843,Hamlet,1913,Walter Ringham,actor,Claudius,1.0
1863174,Hamlet,1913,A. Roberts,actor,Marcellus,11.0
3322807,Hamlet,1913,Olive Richardson,actress,Player Queen,NaN
1515998,Hamlet,1913,R. Montague,actor,Priest,19.0
930908,Hamlet,1913,George Hayes,actor,Osric,10.0
1977523,Hamlet,1913,Alex Scott-Gatty,actor,Laertes,5.0
174961,Hamlet,1913,Grendon Bentley,actor,Fortinbras,7.0
132982,Hamlet,1913,J.H. Barnes,actor,Polonius,4.0
1913254,Hamlet,1913,Montagu Rutherford,actor,Rosencrants,8.0
2747352,Hamlet,1913,Gertrude Elliot,actress,Ophelia,21.0
13907,Hamlet,1913,Eric Adeney,actor,Reynaldo,14.0
2557672,Hamlet,1913,Adeleine Bourne,actress,Gertrude,20.0
1702498,Hamlet,1913,S.T. Pearce,actor,Second Gravedigger,18.0
655321,Hamlet,1913,E. Ericson,actor,Francisco,13.0
447543,Hamlet,1913,S.A. Cookson,actor,Horatio,3.0
52487,Hamlet,1913,Richard Andean,actor,Second Player,16.0
1893671,Hamlet,1913,E.A. Ross,actor,Guildenstern,9.0
1916634,Hamlet,1913,J.H. Ryley,actor,First Gravedigger,17.0
535307,Hamlet,1921,Anton De Verdier,actor,Laertes,7.0
2935728,Hamlet,1921,Lilly Jacobson,actress,Ophelia,8.0
...,...,...,...,...,...,...
2374707,Hamlet,2011,Peter Wingfield,actor,Claudius,3.0
1804123,Hamlet,2011,Bruce Ramsay,actor,Hamlet,1.0
1865653,Hamlet,2011,Russell Roberts,actor,King Hamlet,NaN
2133184,Hamlet,2011,Haig Sutherland,actor,Laertes,NaN
2033697,Hamlet,2011,Martin Sims,actor,Guildenstern,NaN
2188900,Hamlet,2011,Michael Tiernan,actor,Policeman,NaN
2502623,Hamlet,2011,Gillian Barber,actress,Gertrude,NaN
352731,Hamlet,2011,John Cassini,actor,Butler,NaN
851219,Hamlet,2015,Dean Gregory,actor,Lucianus,14.0
2586750,Hamlet,2015,Michelle Butterly,actress,1st Gravedigger,11.0
2533209,Hamlet,2015,Gillian Bevan,actress,Polonia,4.0
2019012,Hamlet,2015,John Shrapnel,actor,Claudius,2.0
2019013,Hamlet,2015,John Shrapnel,actor,Ghost,2.0
80019,Hamlet,2015,Thomas (II) Arnold,actor,Horatio,5.0
2036771,Hamlet,2015,Peter Singh,actor,Guildenstern,9.0
1592747,Hamlet,2015,Tachia Newall,actor,Priest,13.0
1592746,Hamlet,2015,Tachia Newall,actor,Reynaldo,13.0
1592745,Hamlet,2015,Tachia Newall,actor,Francisco,13.0
2523532,Hamlet,2015,Claire Benedict,actress,Player King,8.0
3562331,Hamlet,2015,Katie (II) West,actress,Ophelia,7.0
2113681,Hamlet,2015,Ben Stott,actor,Bernardo,12.0
2113682,Hamlet,2015,Ben Stott,actor,Osric,12.0
2113683,Hamlet,2015,Ben Stott,actor,Player Queen,12.0
2523531,Hamlet,2015,Claire Benedict,actress,Marcella,8.0
3110915,Hamlet,2015,Barbara Marten,actress,Gertrude,3.0
3256505,Hamlet,2015,Maxine Peake,actress,Hamlet,1.0
3137189,Hamlet,2015,Jodie McNee,actress,Rosencrantz,10.0
3137190,Hamlet,2015,Jodie McNee,actress,2nd Gravedigger,10.0
2428915,Hamlet,2015,Ashley Zhangazha,actor,Laertes,6.0
2586749,Hamlet,2015,Michelle Butterly,actress,Margaret,11.0

### List all of the "Treasure Island" movies from earliest to most recent.

In [83]:
cast[cast.title=="Treasure Island"].sort_values('year')

,title,year,name,type,character,n
830114,Treasure Island,1918,Charles Gorman,actor,Prologue Player,NaN
840745,Treasure Island,1918,Joe Grant,actor,Undetermined child role,NaN
909157,Treasure Island,1918,Edwin Harley,actor,Prologue Player,NaN
3298306,Treasure Island,1918,Violet Radcliffe,actress,Long John Silver,3.0
1715014,Treasure Island,1918,Lloyd Perl,actor,Black Dog,4.0
3553298,Treasure Island,1918,Eleanor Washington,actress,Prologue Player,NaN
339256,Treasure Island,1918,Francis Carpenter,actor,Jim Hawkins,1.0
1261579,Treasure Island,1918,Raymond Lee,actor,Bit Role,NaN
1291387,Treasure Island,1918,Elmo Lincoln,actor,Prologue Player,NaN
1946119,Treasure Island,1918,Lewis Sargent,actor,Ben Gunn,5.0
2654214,Treasure Island,1918,Virginia Lee Corbin,actress,Louise Trelawney,2.0
1417884,Treasure Island,1918,Herschel Mayall,actor,Prologue Player,NaN
1473574,Treasure Island,1918,Buddy Messinger,actor,Captain Smolett,6.0
1638400,Treasure Island,1920,Charles Ogle,actor,Long John Silver,6.0
374597,Treasure Island,1920,Lon Chaney,actor,Blind Pew,5.0
1358420,Treasure Island,1920,Charles Hill Mailes,actor,Dr. Livesey,11.0
1516354,Treasure Island,1920,Bull Montana,actor,Morgan,8.0
537825,Treasure Island,1920,Sydney Deane,actor,Squire Trelawney,10.0
977651,Treasure Island,1920,Harry Holden,actor,Capt. Smollett,9.0
374598,Treasure Island,1920,Lon Chaney,actor,Merry,5.0
2006457,Treasure Island,1920,Thomas William Sheffield,actor,Man going over Plank,NaN
700670,Treasure Island,1920,Al W. Filson,actor,Bill Bones,3.0
2037631,Treasure Island,1920,Joseph Singleton,actor,Israel Hands,7.0
3116605,Treasure Island,1920,Shirley Mason,actress,Jim Hawkins,1.0
3142561,Treasure Island,1920,Josie Melville,actress,Mrs. Hawkins,2.0
2164752,Treasure Island,1920,Wilton Taylor,actor,Black Dog,4.0
2088694,Treasure Island,1920,Eli Stanton,actor,Pirate,NaN
883644,Treasure Island,1934,Frank Hagney,actor,Pirate,NaN
3305357,Treasure Island,1934,Ethel Ransome,actress,Streetwalker,NaN
963220,Treasure Island,1934,Jack (II) Hill,actor,Pirate,NaN
...,...,...,...,...,...,...
353505,Treasure Island,1985,Lou Castel,actor,Father,6.0
2122835,Treasure Island,1985,Jean-Fran?ois St?venin,actor,Israel Hands (The Rat),7.0
353504,Treasure Island,1985,Lou Castel,actor,Doctor,6.0
2160278,Treasure Island,1985,Vic Tayback,actor,Silver,1.0
1762501,Treasure Island,1985,Melvil Poupaud,actor,Jim Hawkins,14.0
688366,Treasure Island,1985,Michel Ferber,actor,Crabb,10.0
3245250,Treasure Island,1999,Lisa Papineau,actress,Diedre,19.0
210668,Treasure Island,1999,Jonah Blechman,actor,The Body,3.0
969021,Treasure Island,1999,George Hirschmann,actor,Admiral,12.0
934507,Treasure Island,1999,Pat Healy,actor,Clark,4.0
880460,Treasure Island,1999,Rio Hackford,actor,Hans,23.0
1959741,Treasure Island,1999,Richard Schave,actor,Man,21.0
3415912,Treasure Island,1999,Rachel Singer,actress,Anna,6.0
872384,Treasure Island,1999,Paul Gutrecht,actor,Some Guy,20.0
3507587,Treasure Island,1999,Guinevere Turner,actress,Evelyn,14.0
1869989,Treasure Island,1999,Scot Thomas Robinson,actor,Jimmy,11.0
3195608,Treasure Island,1999,Suzy Nakamura,actress,Yo-Ji,5.0
114904,Treasure Island,1999,Lance (II) Baker,actor,Frank,1.0
445745,Treasure Island,1999,Becket Cook,actor,The Gent,13.0
2931880,Treasure Island,1999,Stephanie Ittleson,actress,Stella,7.0
2865358,Treasure Island,1999,Daisy Hall,actress,Penny,8.0
589900,Treasure Island,1999,Jamie Donovan,actor,John,21.0
2660575,Treasure Island,1999,Nigel (II) Cox,actress,Enid,22.0
1161085,Treasure Island,1999,Scott King,actor,Walter,15.0
1975279,Treasure Island,1999,Dolph Scott,actor,Parker,11.0
2420089,Treasure Island,1999,Caveh Zahedi,actor,Harold,9.0
1637661,Treasure Island,1999,Nick Offerman,actor,Samuel,2.0
1375015,Treasure Island,1999,J.P. Manoux,actor,Officer Hughes,18.0
1797264,Treasure Island,1999,Victor Raider-Wexler,actor,Samowitz,10.0
307749,Treasure Island,1999,Bob Byington,actor,Thomas,12.0

### How many movies were made in the year 1950?

In [84]:
len(cast[cast.year==1950])

22006

### How many movies were made in the year 1960?

In [85]:
len(cast[cast.year==1960])

18456

In [86]:
cast[cast.year==1960]

,title,year,name,type,character,n
68,De zaak M.P.,1960,Frans 't Hoen,actor,Hollandse boer,29.0
115,Thunder in Carolina,1960,2nd Marine Division Band,actor,Themselves,NaN
133,Noi duri,1960,5 Asternovas,actor,Police Officers disguised as Musicians,11.0
265,Sri Venkateswara Mahatmyam,1960,Subba Rao A.V. Jr.,actor,Brahma,10.0
268,Sri Venkateswara Mahatmyam,1960,Subba Rao A.V.,actor,Akasa Raju,5.0
965,Stublenskite lipi,1960,Dimitar Abadzhiev,actor,Georgi,12.0
1388,Malak wa shaitan,1960,Rushdy Abaza,actor,Ezzat,1.0
1495,Sunrise at Campobello,1960,Abdullah Abbas,actor,Convention Delegate,NaN
3299,Arashi o yobu gakudan,1960,T?ru Abe,actor,?nuki,NaN
3303,Fuefukigawa,1960,T?ru Abe,actor,Katsuyan,12.0
4198,Kardakar,1960,K. Abesadze,actor,Besarioni,4.0
4663,Cone of Silence,1960,William Abney,actor,First Officer,12.0
4668,Never Take Sweets from a Stranger,1960,William Abney,actor,1st Policeman,33.0
4671,The City of the Dead,1960,William Abney,actor,Policeman,13.0
4676,Two Way Stretch,1960,William Abney,actor,Visiting Room Warder,17.0
5006,Bhakt Raj,1960,David (II) Abraham,actor,Jatashankar,NaN
5007,Bindya,1960,David (II) Abraham,actor,Rai Saheb Kedarnath,4.0
5017,Ek Phool Char Kaante,1960,David (II) Abraham,actor,Uncle - Cinema Fanatic,5.0
5043,Manzil,1960,David (II) Abraham,actor,Shyam,15.0
5066,Return of Mr. Superman,1960,David (II) Abraham,actor,Boss,7.0
5550,Pluzum,1960,Khoren Abrahamyan,actor,Vardan,2.0
5601,Papa Gigia,1960,Soso Abramashvili,actor,Jabuka,4.0
5608,Zvigenis kbili,1960,Arsen Abramishvili,actor,Husein,8.0
7060,Los tigres del ring,1960,Luis Aceves Casta?eda,actor,Sr. Rosas,NaN
7061,Macario,1960,Luis Aceves Casta?eda,actor,Verdugo infartado,NaN
7074,Bala perdida,1960,Miguel Aceves Mej?a,actor,Carmelo Torres,1.0
7086,Los fanfarrones,1960,Miguel Aceves Mej?a,actor,Miguel,1.0
7091,Tres angelitos negros,1960,Miguel Aceves Mej?a,actor,?ngel Reynosa,1.0
7707,Kyk na die Sterre,1960,Jan (II) Ackerman,actor,Barend,4.0
7923,The Alamo,1960,Ray Ackland,actor,Travis' Man,NaN
...,...,...,...,...,...,...
3606046,Ilze,1960,Margarita Zhigunova,actress,Ilze,1.0
3606048,Zhestokost,1960,Margarita Zhigunova,actress,Yulka Maltseva,NaN
3606164,Xiao niao yi ren,1960,Manhua Zhou,actress,Ji Shun-hua,NaN
3606177,Wu cai lu,1960,Ting Zhou,actress,Mistress Ren,NaN
3606280,Bi bo xian lu,1960,Li Zhu,actress,Guanyin,NaN
3606304,Xiang yang hua kai,1960,Sha Zhu,actress,Feng Axiang,NaN
3606380,Devichya vesna,1960,Garen Zhukovskaya,actress,Anna Lugovaya,4.0
3606383,Voskreseniye,1960,L. Zhukovskaya,actress,Missi Korchagina,31.0
3606781,Strafbataillon 999,1960,Sonja Ziemann,actress,Julia Deutschmann,1.0
3606956,Dilizansa snova,1960,Jelena Zigon,actress,Ciganka,NaN
3606968,Ljubav i moda,1960,Jelena Zigon,actress,Vera,15.0
3607026,Agapoula mou,1960,Antzela Zileia,actress,Hristina,1.0
3607029,Ftohoula kai to vasilopoulo,1960,Antzela Zileia,actress,Aliki,1.0
3608094,Ferragosto in bikini,1960,Nietta Zocchi,actress,La signora Porro,16.0
3608112,Mariti in pericolo,1960,Nietta Zocchi,actress,Madre di Elena,5.0
3608249,Malamo,1960,Sonia Zoidou,actress,Malamo,1.0
3608440,Genitori in blue-jeans,1960,Lia Zoppelli,actress,Wanda,13.0
3608443,Il vigile,1960,Lia Zoppelli,actress,Moglie del sindaco,7.0
3608809,Las furias,1960,Olga Zubarry,actress,Amante,2.0
3609141,Malak wa shaitan,1960,Eman Zulfakar,actress,Sawsan,6.0
3609359,X-25 javlja,1960,Iva Zupancic,actress,Trude,7.0
3609545,Russkiy suvenir,1960,Anastasiya Zuyeva,actress,Yegorkina,9.0
3609548,Voskreseniye,1960,Anastasiya Zuyeva,actress,Matryona Kharina,18.0
3609854,Chlap jako hora,1960,Stella Z?zvorkov?,actress,Maresov? - crane driver,4.0
3610129,A tiro limpio,1960,Sof?a ?lvarez,actress,Norte?a,2.0
3610216,Domaren,1960,Inga-Lill ?hstr?m,actress,Nurse,NaN
3610248,Alla vi barn i Bullerbyn,1960,Kim ?sberg,actress,Britta,NaN
3610684,Kawaita mizuumi,1960,Yachiyo ?tori,actress,Shizue,6.0
3611050,Omringet,1960,Kari ?ksnevad,actress,Anne Aulie,2.0
3611127,Venner,1960,Bibba ?ygard,actress,Kontordame,NaN

### How many movies were made from 1950 through 1959?

In [87]:
len(cast[(cast.year>=1950) & (cast.year<=1959)])

210986

### In what years has a movie titled "Batman" been released?

In [101]:
cast[cast.title=='Batman'].sort_values('year')['year'].unique()

array([1943, 1989], dtype=int64)

### How many roles were there in the movie "Inception"?

In [102]:
len(cast[cast.title=="Inception"])

77

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [113]:
cast[cast.title=="Inception"]['n'].isnull().sum()

26

### But how many roles in the movie "Inception" did receive an "n" value?

In [115]:
cast[cast.title=="Inception"]['n'].notnull().sum()

51

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [142]:
cast[cast.title=="North by Northwest"].sort_values('n').dropna()

,title,year,name,type,character,n
840374,North by Northwest,1959,Cary Grant,actor,Roger O. Thornhill,1.0
3361396,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2.0
1404704,North by Northwest,1959,James Mason,actor,Phillip Vandamm,3.0
3024085,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4.0
343701,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5.0
2923056,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6.0
1634552,North by Northwest,1959,Philip Ober,actor,Lester Townsend,7.0
1229083,North by Northwest,1959,Martin Landau,actor,Leonard,8.0
2357939,North by Northwest,1959,Adam Williams,actor,Valerian,9.0
1746383,North by Northwest,1959,Edward Platt,actor,Victor Larrabee,10.0
642085,North by Northwest,1959,Robert Ellenstein,actor,Licht,11.0
2212083,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12.0
447893,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13.0
1454363,North by Northwest,1959,Patrick McVey,actor,Sergeant Flamm,14.0
198496,North by Northwest,1959,Edward Binns,actor,Captain Junket,15.0
1334726,North by Northwest,1959,Ken Lynch,actor,Charley - Chicago Policeman,16.0

In [143]:
cast[cast.title=="North by Northwest"].sort_values('n').dropna()['name']

840374               Cary Grant
3361396         Eva Marie Saint
1404704             James Mason
3024085     Jessie Royce Landis
343701           Leo G. Carroll
2923056    Josephine Hutchinson
1634552             Philip Ober
1229083           Martin Landau
2357939           Adam Williams
1746383            Edward Platt
642085        Robert Ellenstein
2212083            Les Tremayne
447893          Philip Coolidge
1454363           Patrick McVey
198496             Edward Binns
1334726               Ken Lynch
Name: name, dtype: object

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [148]:
cast[(cast.title=='Sleuth')&(cast.year==1972)].sort_values('n')

,title,year,name,type,character,n
1644328,Sleuth,1972,Laurence Olivier,actor,Andrew Wyke,1.0
314691,Sleuth,1972,Michael Caine,actor,Milo Tindle,2.0
360365,Sleuth,1972,Alec Cawthorne,actor,Inspector Doppler,3.0
1412647,Sleuth,1972,John (II) Matthews,actor,Detective Sergeant Tarrant,4.0
2619278,Sleuth,1972,Eve (III) Channing,actress,Marguerite Wyke,5.0
1396572,Sleuth,1972,Teddy Martin,actor,Police Constable Higgs,6.0

In [149]:
cast[(cast.title=='Sleuth')&(cast.year==1972)].sort_values('n')['name']

1644328      Laurence Olivier
314691          Michael Caine
360365         Alec Cawthorne
1412647    John (II) Matthews
2619278    Eve (III) Channing
1396572          Teddy Martin
Name: name, dtype: object

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [151]:
cast[(cast.title=='Sleuth')&(cast.year==2007)].sort_values('n')

          title  year                 name     type          character    n
314692   Sleuth  2007        Michael Caine    actor             Andrew  1.0
1246855  Sleuth  2007             Jude Law    actor               Milo  2.0
1741124  Sleuth  2007        Harold Pinter    actor        Man on T.V.  3.0
250297   Sleuth  2007      Kenneth Branagh    actor  Other Man on T.V.  NaN
360366   Sleuth  2007  Alec (II) Cawthorne    actor  Inspector Doppler  NaN
2619277  Sleuth  2007    Eve (II) Channing  actress    Marguerite Wyke  NaN
3223502  Sleuth  2007    Carmel O'Sullivan  actress             Maggie  NaN

In [153]:
cast[(cast.title=='Sleuth')&(cast.year==2007)].sort_values('n')['name']

314692           Michael Caine
1246855               Jude Law
1741124          Harold Pinter
250297         Kenneth Branagh
360366     Alec (II) Cawthorne
2619277      Eve (II) Channing
3223502      Carmel O'Sullivan
Name: name, dtype: object

### How many roles were credited in the silent 1921 version of Hamlet?

In [217]:
cast[(cast.title=='Hamlet')&(cast.year==1921)]['character'].nunique()

9

### How many roles were credited in Branagh’s 1996 Hamlet?

In [165]:
cast[(cast.title=='Hamlet')&(cast.year==1996)]

,title,year,name,type,character,n
1615,Hamlet,1996,Riz Abbasi,actor,Attendant to Claudius,1.0
92106,Hamlet,1996,Richard Attenborough,actor,English Ambassador,2.0
152349,Hamlet,1996,Simon Russell Beale,actor,Second Gravedigger,37.0
206181,Hamlet,1996,David (V) Blair,actor,Attendant to Claudius,3.0
211111,Hamlet,1996,Brian Blessed,actor,Ghost of Hamlet's Father,4.0
241315,Hamlet,1996,Christopher Bowles,actor,Cadet in Play,NaN
250281,Hamlet,1996,Kenneth Branagh,actor,Hamlet,5.0
262368,Hamlet,1996,Richard Briers,actor,Polonius,6.0
283598,Hamlet,1996,Michael Bryant,actor,Priest,7.0
307699,Hamlet,1996,Peter Bygott,actor,Attendant to Claudius,8.0
331657,Hamlet,1996,Kenneth W Caravan,actor,Laertes Mob,NaN
482982,Hamlet,1996,Billy Crystal,actor,First Gravedigger,10.0
500005,Hamlet,1996,Charles Daish,actor,Stage Manager,11.0
555725,Hamlet,1996,G?rard Depardieu,actor,Reynaldo,13.0
577284,Hamlet,1996,Reece Dinsdale,actor,Guildenstern,14.0
582748,Hamlet,1996,Ken Dodd,actor,Yorick,15.0
633587,Hamlet,1996,Rob Edwards,actor,Lucianus,17.0
645509,Hamlet,1996,Jimmy Ellis,actor,Old Fortinbras,NaN
679290,Hamlet,1996,Nicholas Farrell,actor,Horatio,18.0
683298,Hamlet,1996,Ray Fearon,actor,Francisco,19.0
797642,Hamlet,1996,John Gielgud,actor,Priam,21.0
955936,Hamlet,1996,Charlton Heston,actor,Player King,23.0
1037016,Hamlet,1996,Ravil Isyanov,actor,Cornelius,24.0
1044207,Hamlet,1996,Derek Jacobi,actor,Claudius,25.0
1167241,Hamlet,1996,Jeffery Kissoon,actor,Fortinbras's Captain,27.0
1269051,Hamlet,1996,Jack Lemmon,actor,Marcellus,29.0
1350198,Hamlet,1996,Anthony Maddalena,actor,Elsinore Courtier,NaN
1366209,Hamlet,1996,Michael Maloney,actor,Laertes,31.0
1435643,Hamlet,1996,Ian McElhinney,actor,Barnardo,30.0
1493790,Hamlet,1996,John Mills,actor,Old Norway,33.0
1500413,Hamlet,1996,Jimi Mistry,actor,Sailor Two,34.0
1531589,Hamlet,1996,Frank (II) Morgan,actor,Pyrrhus,NaN
1966605,Hamlet,1996,Andrew Schofield,actor,Young Lord,38.0
1978967,Hamlet,1996,Orlando Seale,actor,Boatman,NaN
1993152,Hamlet,1996,Rufus Sewell,actor,Fortinbras,39.0
2073370,Hamlet,1996,Timothy Spall,actor,Rosencrantz,40.0
2076719,Hamlet,1996,John Spencer-Churchill,actor,Fortinbras's Captain,32.0
2141264,Hamlet,1996,Thomas Szekeres,actor,Young Hamlet,41.0
2177460,Hamlet,1996,Ben Thom,actor,First Player,42.0
2316164,Hamlet,1996,Don Warrington,actor,Voltimand,43.0
2363858,Hamlet,1996,Robin Williams,actor,Osric,45.0
2409119,Hamlet,1996,David Yip,actor,Sailor One,47.0
2417104,Hamlet,1996,Jimmy Yuill,actor,Alexander,NaN
2631662,Hamlet,1996,Julie Christie,actress,Gertrude,9.0
2703468,Hamlet,1996,Judi Dench,actress,Hecuba,12.0
2723751,Hamlet,1996,Angela Douglas,actress,Attendant to Gertrude,16.0
2821440,Hamlet,1996,Yvonne Gidden,actress,Doctor,20.0
2877400,Hamlet,1996,Rosemary Harris,actress,Player Queen,22.0
2989168,Hamlet,1996,Rowena King,actress,Attendant to Gertrude,26.0
3021294,Hamlet,1996,Sarah Lam,actress,Attendant to Gertrude,28.0
3298558,Hamlet,1996,Sian Radinger,actress,Prologue,35.0
3303304,Hamlet,1996,Melanie Ramsay,actress,Prostitute,NaN
3557773,Hamlet,1996,Perdita Weeks,actress,Second Player,44.0
3578802,Hamlet,1996,Kate Winslet,actress,Ophelia,46.0

In [167]:
cast[(cast.title=='Hamlet')&(cast.year==1996)&(cast.name=='Kenneth Branagh')]

         title  year             name   type character    n
250281  Hamlet  1996  Kenneth Branagh  actor    Hamlet  5.0

In [168]:
len(cast[(cast.title=='Hamlet')&(cast.year==1996)&(cast.name=='Kenneth Branagh')])

1

### How many "Hamlet" roles have been listed in all film credits through history?

In [215]:
cast[(cast.title=='Hamlet')]['character'].nunique()

107

### How many people have played an "Ophelia"?

In [174]:
len(cast[cast.character=='Ophelia'])

111

In [213]:
cast[cast.character=='Ophelia']['name'].nunique()

109

### How many people have played a role called "The Dude"?

In [211]:
cast[cast.character=='The Dude']['name'].nunique()

18

### How many people have played a role called "The Stranger"?

In [209]:
cast[cast.character=='The Stranger']['name'].nunique()

197

In [212]:
cast[cast.character=='The Stranger']['name'].unique()

array(['Hassan Mutlag Al-Maraiyeh', 'Vincent H. Alexander',
       'Tony Anthony', 'Phil Arnold', 'Ryan Andrew Balas', 'Cristi Balea',
       'Richard Baron', 'Nigel Barrett', 'Harry Basch', 'Arben Biba',
       'Richard (XV) Bishop', 'Frank Borzage', 'Pinkas Braun',
       'Gerard Butler', 'Nicholas Campbell', 'Nik Catello',
       'Lyster Chambers', 'Michael V. Chastain', 'Chazz', 'Alan Christy',
       'Jason (VII) Coleman', 'Hallam Cooley', 'Sharlto Copley',
       'Ste Cork', 'Gino Corrado', 'Harp Corrigan', 'Walter Coy',
       'Shawn Crosby', 'Jemo Dalipovic', 'Matt Danner', 'Helmut Dantine',
       'Josh Davidson', 'William B. Davidson', 'Jim Davis',
       'Ben (V) Dawson', 'Michael Dawu', 'Tim DeKay', 'Patrick Dempsey',
       'Joe DeRita', 'Alex Diakun', 'Billy Drago', 'Tex Driscoll',
       'Rainer D?sing', 'Eddie Eagle', 'Clint Eastwood',
       'James L. Edwards', 'Sam Elliott', 'Alberto Esparza',
       'Manuchehr Farid', 'Michael Ian Farrell', 'George Fawcett',
       'Federico Fellini', 'James Stephen Finn', "Maurice 'Lefty' Flynn",
       'Johnston Forbes-Robertson', 'Francis Ford', 'Ben Foster',
       'Robert Frazer', 'Ralph (II) Freedman', 'Mark Fucile',
       'Courtney Gains', 'J?zsef Gallai', 'Sammy Gilbert', 'J.H. Gilmour',
       'Josue Guerra', 'Sid Haig', 'Jenny Haining', 'Justin (VIII) Hall',
       'C.M. Hallard', 'Troy Halverson', 'Gunnar (II) Hansen',
       'Ty Hardin', 'Michael Harrelson', 'Jonathan Haug', 'Edward Hearn',
       'Lance Henriksen', 'Dan Hicks', 'George Hilton', 'Lee Horsley',
       'Kevin Howarth', 'Chad (XIII) Johnson', 'Jeff Joslin', 'Axel Kaae',
       'Manav Kaushik', 'Michael Kennelty', 'Charles Kent', 'Irwin Keyes',
       'Udo Kier', 'Andrew (II) Kines', 'William Kozy', 'Jun Kunimura',
       'Darwin Lamb', 'Mike (VI) Lambert', 'C.S. Lee', 'Nick Leos',
       'Joseph Levering', 'Elmo Lincoln', 'Lucien Littlefield',
       'Andrew Espinoza Long', 'Peter Lorre', 'Wallace MacDonald',
       'D.G. Maloney', 'Nick Mancuso', 'Marilyn Manson', 'Ed Mantell',
       'Bruce Marchiano', 'Mike (III) Marino', 'Tully Marshall',
       'John Wills Martin', 'Kingsly Martin', 'Ryan McGivern',
       'Aaron McGrane', 'Richard (II) McNamara', 'Tomas Milian',
       'Jefferson Moore', 'John (III) Moore', 'Matthew Moy', 'Uns Mufti',
       'Morgan Muscat', 'Timothy Muskatell', 'Wade Mylius',
       'Steve Noettl', 'Michael (III) Nolan', 'Ken Nordine',
       'Harry Northrup', 'Bill Oberst Jr.', 'Ricky Onsgard',
       'Deobia Oparei', 'William Orlamond', 'Michael Otis',
       'Gary (III) Owen', 'Anthony Oyeola', 'Bradley Page',
       'Michael Pasternak', 'Bill Patton', 'Frantisek Paul',
       'George C. Pearce', 'Jack Perrin', 'Ralph Peters', 'William Pike',
       'Purnell Pratt', 'Wojciech Pszoniak', 'John Qualen',
       'Randy Raphael', 'Matthew Rauch', 'Jake Red', 'Shivam Reddington',
       'Brad Renfro', 'Alveraz Ricardez', 'Steven (II) Richards',
       'Darren Ripley', 'Tim Robbins', 'North Roberts', 'Karel Roden',
       'Don Rowe', 'Aleksandr Rumnyov', 'Philippe Saba',
       'Monroe Salisbury', 'Matthew Luke Sandoval', 'Martin Sheen',
       'George Shevtsov', 'Bernard Siegel', 'Joe Sinclitico',
       'Gustaf Skarsg?rd', 'Robert Skene', 'Herb Smith', 'Kevin Sorbo',
       'Ron (III) Spencer', 'Marco St. John', 'David Strathairn',
       'Leonard Strong', 'Suman', 'Kiefer Sutherland', 'Harry Tenbrook',
       'Arthur Thalasso', 'Zachary Throne', 'Peng Tien', 'Ben Turpin',
       'Anders Van Haden', 'Brian VanDyke', 'Antonis Varkaris',
       'Conrad Veidt', 'Emmett Vogan', 'Millard K. Wilson',
       'Maurice Dean Wint', 'Steve Yahnke', 'Chun Yang', 'Derrick Yeoman',
       'Patricia Darling', 'Lida Duch', 'Adrienne King', 'Sophia Knolton',
       'Kathy Long', 'Ethel Lynne', 'Rosa Maria Paz', 'Angela Pleasence',
       'Dorinea Shirley'], dtype=object)

### How many roles has Sidney Poitier played throughout his career?

In [203]:
cast[cast.name=='Sidney Poitier']['character'].unique()

array(['Gordon Ralfe', 'Manny Durrell', 'Walter Lee Younger',
       'Dr. Matt Younger', 'Sgt. Eddie Towler', 'Rau-Ru',
       'Gregory W. Miller', 'John Kane', 'Buck', 'Reverend Msimangu',
       'Toller', 'Tommy Tyler', 'Jack Parks', 'Inman Jackson',
       'Gates Watson', 'John Prentice', 'Virgil Tibbs', 'Clyde Williams',
       'Homer Smith', 'Roy Parmenter', 'Dr. Luther Brooks', 'Eddie Cook',
       'Porgy', 'Doctor', 'Robertson', 'Night Club Extra',
       'Warren Stantin', 'Donald Crease', 'Kimani Wa Karanja',
       'Ben Munceford', 'Noah Cullen', 'Simon of Cyrene',
       'FBI Deputy Director Carter Preston', 'Aly Mansuh', 'Jason Higgs',
       'Obam', 'Alan Newell', 'Shack Twala', 'Mark Thackeray',
       'Steve Jackson', 'Marcus'], dtype=object)

In [204]:
cast[cast.name=='Sidney Poitier']['character'].nunique()

41

### How many roles has Judi Dench played?

In [201]:
cast[cast.name=='Judi Dench']['character']

2703455                        Nora Doel
2703456                      Mrs. Beaver
2703457                          Titania
2703458       Eleanor Lavish, a novelist
2703459                            Sally
2703460                       Miss Lilly
2703461                                M
2703462                   Armande Voizin
2703463                   Laura Davidson
2703464                                M
2703465                         Narrator
2703466                             Wife
2703467                                M
2703468                           Hecuba
2703469                           Joanne
2703470            Mistress Nell Quickly
2703471                     Mrs. Caloway
2703472                     Iris Murdoch
2703473                     Annie Hoover
2703474                         Margaret
2703475                     Mrs. Fairfax
2703476                          Paulina
2703477                           Ursula
2703478                        Katherine
2703479                      Miss Avocet
2703480                   Queen Victoria
2703481             Mrs. Laura Henderson
2703482             Princess Dragomiroff
2703483             Dame Sybil Thorndike
2703484                            Lilli
2703485                   Barbara Covett
2703486                        Philomena
2703487                     Society Lady
2703488          Lady Catherine de Bourg
2703489                                M
2703490                     Mona Carvell
2703491                         Bag Lady
2703492                     The Narrator
2703493                  Queen Elizabeth
2703494                                M
2703495                                M
2703496                             Mary
2703497                         Arabella
2703498    Shakespeare's Sonnets read by
2703499                Evelyn Greenslade
2703500                           Aereon
2703501                   Lady Bracknell
2703502                Evelyn Greenslade
2703503                       Agnis Hamm
2703504                   Miss Humphries
2703505                                M
2703506                                M
2703507         The Abbess of St. Ursula
2703508                   Queen Victoria
2703509                Marcia Pilborough
Name: character, dtype: object

In [200]:
cast[cast.name=='Judi Dench']['character'].nunique()

46

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [181]:
cast[(cast.name=='Cary Grant')&(cast.year==1940)&(cast.n==2.0)]

                   title  year        name   type character    n
840371  My Favorite Wife  1940  Cary Grant  actor      Nick  2.0

In [183]:
len(cast[(cast.name=='Cary Grant')&(cast.year==1940)&(cast.n==2.0)])

1

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [187]:
cast[(cast.name=='Cary Grant')&(cast.year==1940)].sort_values('year')

,title,year,name,type,character,n
840353,His Girl Friday,1940,Cary Grant,actor,Walter Burns,1.0
840371,My Favorite Wife,1940,Cary Grant,actor,Nick,2.0
840397,The Howards of Virginia,1940,Cary Grant,actor,Matt Howard,1.0
840399,The Philadelphia Story,1940,Cary Grant,actor,C. K. Dexter Haven,1.0

In [196]:
cast[(cast.name=='Cary Grant')&(cast.year==1940)].sort_values('year')['character']

840353          Walter Burns
840371                  Nick
840397           Matt Howard
840399    C. K. Dexter Haven
Name: character, dtype: object

### How many roles were available for actors in the 1950s?

In [194]:
cast[cast.year==1950].sort_values('character')['character'].unique()

array([' Durango Kid', ' Priest', "'45 Jones", ..., 'novillero',
       'von Aster', 'von Stoffel'], dtype=object)

In [195]:
cast[cast.year==1950].sort_values('character')['character'].nunique()

15007

### How many roles were available for actresses in the 1950s?

In [220]:
cast[(cast.type=='actress')&(cast.year==1950)]['character'].unique()

array(['Apache Dancers', 'Model', 'Carriage Woman', ...,
       'Do?a Blanquita Z??iga de Vallarta', 'May Takebayashi',
       'Summer Camp Manager'], dtype=object)

In [221]:
cast[(cast.type=='actress')&(cast.year==1950)]['character'].nunique()

4052

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [223]:
cast[(cast.n==1)&(cast.year<=1980)]['character'].nunique()

51200

In [224]:
cast[(cast.n==1)&(cast.year<=1980)]

,title,year,name,type,character,n
277,En glad gutt,1932,Hauk Aabel,actor,Ola Nordistua,1.0
282,En herre med bart,1942,Per Aabel,actor,"Ole Grong, advokat",1.0
1026,Batman Fights Dracula,1967,Jing Abalos,actor,Batman,1.0
1027,Batman Fights Dracula,1967,Jing Abalos,actor,Bruce Wayne,1.0
1031,Mighty Rock,1969,Jing Abalos,actor,Mighty Rock,1.0
1121,"Ar Daijero, Rom agar var",1975,Dodo Abashidze,actor,Mikho,1.0
1126,Didi mtsvane veli,1967,Dodo Abashidze,actor,Sosana,1.0
1131,Kvarkvare,1978,Dodo Abashidze,actor,Kvarkavre Tutaberi,1.0
1139,Pirveli mertskhali,1975,Dodo Abashidze,actor,Jasoni,1.0
1142,Sinatle chvens panjrebshi,1969,Dodo Abashidze,actor,Aleqsandre,1.0
1147,Tsimbireli papa,1974,Dodo Abashidze,actor,Nestor,1.0
1154,Glakhis naambobi,1961,Gocha Abashidze,actor,Gabro,1.0
1221,Il pap'occhio,1980,Diego Abatantuono,actor,Padre Gabriele,1.0
1369,A World of Chirldren,1976,Rushdy Abaza,actor,Helmy,1.0
1374,Athkiya' laken aghbiya',1980,Rushdy Abaza,actor,Hamdi,1.0
1379,El mushajibun,1966,Rushdy Abaza,actor,Amin,1.0
1388,Malak wa shaitan,1960,Rushdy Abaza,actor,Ezzat,1.0
1630,Bir qalanin sirri,1959,Gyunduz Abbasov,actor,Elsan,1.0
1743,Il pleut sur Santiago,1975,John Abbey,actor,L'agent am?ricain,1.0
1744,Il pleut sur Santiago,1975,John Abbey,actor,CIA Agent,1.0
1873,Abbott and Costello Go to Mars,1953,Bud Abbott,actor,Lester,1.0
1874,Abbott and Costello in the Foreign Legion,1950,Bud Abbott,actor,Bud Jones,1.0
1875,Abbott and Costello Meet Captain Kidd,1952,Bud Abbott,actor,Rocky Stonebridge,1.0
1876,Abbott and Costello Meet Dr. Jekyll and Mr. Hyde,1953,Bud Abbott,actor,Slim,1.0
1877,Abbott and Costello Meet the Invisible Man,1951,Bud Abbott,actor,Bud Alexander,1.0
1878,Abbott and Costello Meet the Keystone Kops,1955,Bud Abbott,actor,Harry 'Slim' Pierce,1.0
1879,"Abbott and Costello Meet the Killer, Boris Kar...",1949,Bud Abbott,actor,Casey Edwards,1.0
1880,Abbott and Costello Meet the Mummy,1955,Bud Abbott,actor,Pete Patterson,1.0
1881,Africa Screams,1949,Bud Abbott,actor,Buzz Johnson,1.0
1882,Buck Privates,1941,Bud Abbott,actor,Slicker Smith,1.0
...,...,...,...,...,...,...
3608661,Syntomo dialeimma,1966,Voula Zouboulaki,actress,Emma Karali,1.0
3608700,Le lit de la vierge,1969,Zouzou,actress,Marie,1.0
3608701,Le lit de la vierge,1969,Zouzou,actress,Marie Magdal?ne,1.0
3608702,Les apprentis sorciers,1977,Zouzou,actress,Clara,1.0
3608801,A hierro muere,1962,Olga Zubarry,actress,Elisa,1.0
3608805,El vampiro negro,1953,Olga Zubarry,actress,Amalia,1.0
3608806,El vampiro negro,1953,Olga Zubarry,actress,Rita,1.0
3608808,La muerte camina en la lluvia,1948,Olga Zubarry,actress,Lila Espinoza,1.0
3608810,Los pulpos,1948,Olga Zubarry,actress,Myrtha,1.0
3608812,Marianela,1955,Olga Zubarry,actress,Marianela,1.0
3608813,Valentina,1950,Olga Zubarry,actress,Valentina Gonz?lez Garc?a,1.0
3608826,Gul-e-Bakavali,1924,Zubeida,actress,Bakavali,1.0
3609369,Cvetje v jeseni,1973,Milena Zupancic,actress,Meta,1.0
3609387,Vdovstvo Karoline Zasler,1976,Milena Zupancic,actress,Karolina Zasler,1.0
3609888,Strach,1975,Joanna Z?lkowska,actress,Agnieszka Pawelczyk,1.0
3609913,El secreto del doctor,1930,Eugenia Z?ffoli,actress,Lillian Garson,1.0
3609947,"Sutyi, a szerencsegyerek",1938,Kl?ri ?d?m,actress,Sutyl,1.0
3609951,Hoheit tanzt Walzer,1935,Ir?n ?gay,actress,Prinzessin Marika,1.0
3610052,Antonia Santos,1944,Lily (II) ?lvarez,actress,Antonia Santos,1.0
3610131,Flor de fango,1942,Sof?a ?lvarez,actress,Marissa,1.0
3610132,La barca de oro,1947,Sof?a ?lvarez,actress,Chabela Vargas,1.0
3610135,Soy charro de Rancho Grande,1947,Sof?a ?lvarez,actress,Cristina,1.0
3610415,La nuit de Sybille,1947,Paulette ?lambert,actress,Sibylle,1.0
3610485,Anego,1969,Hiroko ?gi,actress,Ai Konno,1.0
3610486,Noboriryu tekkahada,1970,Hiroko ?gi,actress,Katsumi Sakura,1.0
3610588,Jokosei: natsu hiraku kuchiburu,1980,Ayako ?ta,actress,Sh?ko Yazaki,1.0
3610590,Kairaku gakuen: kinjirareta asobi,1980,Ayako ?ta,actress,Sachiko Suzuki,1.0
3610607,Ah! Nomugi toge,1979,Shinobu ?take,actress,Mine Masai,1.0
3610750,Kvinnolek,1968,Gunbritt ?hrstr?m,actress,"Lisa Holmberg, fashion designer",1.0
3610795,Tamam mi devam mi?,1975,F?sun ?nal,actress,F?sun,1.0

### How many non-leading roles were available through from the beginning of film history through 1980?

In [225]:
cast[(cast.n!=1)&(cast.year<=1980)]['character'].nunique()

558711

In [226]:
cast[(cast.n!=1)&(cast.year<=1980)].head()

,title,year,name,type,character,n
20,Natas es Satan,1977,Ramon 'Cartucho' Pena,actor,Nigth Club Owner,NaN
32,Los tarantos,1963,'El Guisa',actor,Bailaor,25.0
34,Los tarantos,1963,'El Viti',actor,Cantaor,20.0
41,Been Down So Long It Looks Like Up to Me,1971,Murray the 'K',actor,Himself,NaN
42,I Wanna Hold Your Hand,1978,Murray the 'K',actor,Himself,48.0

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [5]:
no_rank=cast[(cast.year<=1980)].fillna(0)

In [11]:
no_rank[(no_rank.n==0)].sort_values('character')['character'].unique()

array([' Alamo defender', ' Avukat', ' Brawler', ..., 'zpevacka Virzinie',
       'zweiter Professor', 'zyat Novosolyova'], dtype=object)

In [13]:
no_rank[(no_rank.n==0)].sort_values('character')['character'].nunique()

186116